routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});

Auth::routes();

Route::get('/home', 'HomeController@index');

Route::middleware(['auth'])->group(function () {

    Route::resource('clientes', 'ClienteController');

    Route::resource('regions', 'RegionController');

    Route::resource('plans', 'PlanController');

    Route::resource('sectorials', 'SectorialController');

    Route::resource('prospectos', 'ProspectoController');

    Route::resource('productos', 'ProductoController');

    Route::resource('gastos', 'GastosController');

    Route::resource('pendientes', 'PendienteController');

    Route::resource('compras', 'ComprasController');

    Route::resource('contratos', 'ContratoController');

    Route::resource('pagos', 'PagoController');

    Route::resource('proveedors', 'ProveedorController');

    Route::resource('users', 'UserController');

    Route::resource('roles', 'RoleController');
    //Rutas auxiliares
    Route::get('/helpers/buscar', 'HelperController@busqueda');

    Route::get('/helpers/buscarProducto', 'HelperController@buscaProducto');

    Route::get('/helpers/verificarExistencias', 'HelperController@verificarStock');

    Route::get('/helpers/buscarContrato', 'HelperController@verificarContrato');

    Route::get('/helpers/buscarFolio', 'HelperController@verificarFolio');

    Route::get('/helpers/buscarSector', 'HelperController@verificarSector');

    Route::get('/helpers/contratoCliente', 'HelperController@contratoCliente');

    Route::get('/helpers/pagoCliente', 'HelperController@pagoCliente');

    Route::get('/helpers/datosCliente', 'HelperController@datosCliente');

    Route::get('/helpers/generarPdf', 'HelperController@generarPdf');

    Route::get('/helpers/respaldar', 'HelperController@respaldar');
});

app/Models/Compras.php
<?php

namespace App\Models;

use Eloquent as Model;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * Class Compras
 * @package App\Models
 * @version April 8, 2020, 3:16 am UTC
 *
 * @property string fecha
 * @property number total
 * @property string proveedor
 * @property string usuario
 */
class Compras extends Model
{
    use SoftDeletes;

    public $table = 'compras';
    

    protected $dates = ['deleted_at'];



    public $fillable = [
        'fecha',
        'total',
        'proveedor',
        'usuario'
    ];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'id' => 'integer',
        'fecha' => 'date',
        'total' => 'double',
        'proveedor' => 'string',
        'usuario' => 'string'
    ];

    /**
     * Validation rules
     *
     * @var array
     */
    public static $rules = [
        'fecha' => 'required',
        'total' => 'required',
        'proveedor' => 'required',
    ];

}

app/Http/Controllers/ComprasController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\CreateComprasRequest;
use App\Http\Requests\UpdateComprasRequest;
use App\Repositories\ComprasRepository;
use App\Http\Controllers\AppBaseController;
use App\Models\Compras;
use Illuminate\Http\Request;
use Flash;
use Prettus\Repository\Criteria\RequestCriteria;
use Response;
use Illuminate\Support\Facades\DB;
use App\Models\Proveedor;
use Illuminate\Support\Facades\Auth;

class ComprasController extends AppBaseController
{
    /** @var  ComprasRepository */
    private $comprasRepository;
    var $STORE;
    var $ERROR;

    public function __construct(ComprasRepository $comprasRepo)
    {
        $this->middleware('permission:compras.index')->only('index');
        $this->middleware('permission:compras.create')->only(['create','store']);
        $this->middleware('permission:compras.show')->only('show');
        $this->comprasRepository = $comprasRepo;
        $this->STORE = 'Datos registrados de forma exitosa';
        $this->ERROR = 'Datos no encontrados';
    }

    /**
     * Display a listing of the Compras.
     *
     * @param Request $request
     * @return Response
     */
    public function index(Request $request)
    {
        //$this->comprasRepository->pushCriteria(new RequestCriteria($request));
        //$compras = $this->comprasRepository->all();
        //$compras = Compras::paginate(10);
        $compras = DB::table('compras')
        ->join('proveedors', 'compras.id_proveedor', '=', 'proveedors.id')
        ->select('compras.id', 'compras.fecha', 'proveedors.nombre', 'compras.total', 'compras.usuario')
        ->paginate(10);
        return view('compras.index')
            ->with('compras', $compras);
    }

    /**
     * Show the form for creating a new Compras.
     *
     * @return Response
     */
    public function create()
    {
        $proveedores = Proveedor::pluck('nombre','id');
        $productos = DB::select('select codigo,descipcion from productos');
        return view('compras.create',compact('productos','proveedores'));
    }

    /**
     * Store a newly created Compras in storage.
     *
     * @param CreateComprasRequest $request
     *
     * @return Response
     */
    public function store(Request $request)
    {
        
      if($request->ajax()){
            DB::beginTransaction();
            try{
                /*09 de abril 2020:esta línea se puso en esta posición, ya que se andaban isertando dos registros a la vez
             *como si el request se ejecutara dos veces, estando dentro de este if
             *solo se ejecuta una vez
             *10 de abril: El mensade de flash success no se ejecutaba por lo que no llegaba el response
             *a la solicitud ajax, entonces cuando se manda el success nos dirige a index
             *y de esa forma el mensaje se visualiza
             */
           // $compras = $this->comprasRepository->create($input);
            
           $fecha= $request->input('fecha');
           $id_proveedor= $request->input('proveedor');
           $total= $request->input('total');
           $usuario= Auth::user()->name;

            DB::insert('insert into compras(fecha
            ,id_proveedor
            ,total
            ,usuario
            ,created_at) values (?,?,?,?,?)',[
            $fecha
            ,$id_proveedor
            ,$total
            ,$usuario
            ,new \Datetime()
            ]);
            //es necesario obtener el ultimo id registrado para ingresarlo a la base de datos
            $id_c= DB::select('select last_insert_id() as id_compra');

            //el resultado de la consulta se vacia en un array, accedemos a el con el indice y la clave
            $id_compra = $id_c[0]->id_compra;
            // es posible asignar los datos a un arreglo con un estilo 'clave'=>'valor'
            //$array=[];
            $producto=json_decode( $request->input('producto'));
            $precio=json_decode( $request->input('precio'));
            $cantidad=json_decode( $request->input('cantidad'));
            $subtotal=json_decode( $request->input('subtotal'));
           
                /*
                 * ya que se pueden insertar varios productos a la vez se usa un bucle,
                 * y por cuestiones de diseño de las tablas de base de datos se inserta primero
                 * la compra, enseguida el detalle de compra 
                 */
                for($i=0;$i<sizeof($producto);$i++){
                    
                    $id_pro = DB::select('select id from productos where codigo = ?', [$producto[$i]]);
                    $id_producto = $id_pro[0]->id;

                    DB::select('call sp_ingresarMercancia (?, ?, ?, ?, ?)',
                    [$id_compra,
                    $id_producto,
                    $cantidad[$i],
                    $precio[$i],
                    $subtotal[$i]]);
                }
          
                DB::commit();

                //respondemos a ajax de exito, para 'notificar' que lo que nos envió llegó correctamente
                return response()->json(['exito'=>'exito']);
                Flash::success($this->STORE);
            }catch(\Exception $e){
                Flash::error('Ha ocurrido un problema');
                DB::rollback();
            }
        } 
        
        return redirect(route('compras.index'));
    }

    /**
     * Display the specified Compras.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function show($id)
    {
        $compras = $this->comprasRepository->findWithoutFail($id);

        if (empty($compras)) {
            Flash::error($this->ERROR);

            return redirect(route('compras.index'));
        }
        $proveedor = DB::select('select nombre from proveedors where id = (select id_proveedor from compras where id = ?)',[$id]);

        $comprasDetalles = DB::select('call sp_detallesCompra(?)',[$id]);

        return view('compras.show',compact('compras','comprasDetalles','proveedor'));
    }

}

resources/views/compras/compra_detalles.blade.php
<!DOCTYPE html>
<html>

<head>
</head>

<body>
    <form id="formProductos" name="formProductos" method="post">

        <div class="col-md-12">
            <div class="box box-primary">
                <div class="box-header">
                    <div class="form-group col-sm-3 pull-right">
                        <label for="fecha">Fecha de compra:</label>
                        <input type="date" name="fecha" class="form-control" id="fecha">
                    </div>
                    <div class="form-group col-sm-3 pull-right">
                        {!! Form::label('proveedor', 'Proveedor:') !!}
                        {!! Form::select('proveedor', $proveedores, null, ['class' => 'form-control']) !!}
                    </div>
                </div>
                <!-- /.box-header -->
                <div class="box-body">
                    <div class="form-group col-sm-3">
                        <label for="producto">Código de producto:</label>
                        <input type="text" name="codigoProducto" class="form-control" id="codigoProducto" style="text-transform: uppercase;">
                        <span id="errorCodigo" style="color: red"></span>
                    </div>
                    <div class="form-group col-sm-3">
                        <label for="cantidad">Cantidad comprada:</label>
                        <input type="number" name="cantidad" class="form-control" id="cantidad" onkeyup="calcularSubtotal()">
                        <span id="errorCantidad" style="color: red"></span>
                    </div>
                    <div class="form-group col-sm-3">
                        <label for="precio">Precio de compra:</label>
                        <input type="number" name="precio" class="form-control" id="precio" step="any" onkeyup="calcularSubtotal()">
                        <span id="errorPrecio" style="color: red"></span>
                    </div>
                    <div class="form-group col-sm-3">
                        <label for="subtotal">Subotal:</label>
                        <input type="text" name="subtotal" class="form-control" id="subtotal" readonly="readonly">
                    </div>

    </form>
    
    <div class="box-body col-sm-12">
        <div class="form-group col-sm-3">
            <input type="button" name="add" class="btn btn-primary" value="Agregar producto" id="add">
        </div>
        <div class="form-group col-sm-3 pull-right">
            <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#modalProductos">
                Mostrar productos registrados
            </button>
        </div>
    </div>

    <table id="tableProductos" name="tableProductos" class="table">
        <tbody>
            <tr>
                <th>No</th>
                <th>Código del producto</th>
                <th>Cantidad comprada</th>
                <th>Precio de compra</th>
                <th>Subtotal</th>
            <tr>
        </tbody>
    </table>
    <div class="form-group col-sm-3 pull-right">
        <label for="total">Total:</label>
        <input type="text" name="total" class="form-control" id="total" readonly="readonly">
    </div>
    <br>
    <div class="form-group col-sm-3">
        <button id="save" data-url="{{route('compras.store')}}" class="btn btn-primary">Guardar</button>
        <a href="{{ route('compras.index') }}" class="btn btn-default">Cancelar</a>
    </div>
    </div>
    <!-- /.box-body -->
    </div>
    <!-- /.box -->
    </div>

</body>

</html>


<!-- Modal -->
<div class="modal fade" id="modalProductos" tabindex="-1" role="dialog" aria-labelledby="exampleModalScrollableTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-scrollable" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div class="table-responsive">
                    <table class="table" id="productos-table">
                        <thead>
                            <tr>
                                <th>Código</th>
                                <th>Descripción</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach($productos as $producto)
                            <tr>
                                <td>{{ $producto->codigo }}</td>
                                <td>{{ $producto->descipcion }}</td>
                            </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

resources/views/compras/create.blade.php
@extends('layouts.app')

@section('content')
<section class="content-header">
    <h1>
        Compras
    </h1>
</section>
<div class="content">
    @include('adminlte-templates::common.errors')

    <input type="hidden" name="_token" value="{{ csrf_token() }}" id="token">
    {!! Form::open(['route' => 'compras.store']) !!}

    @include('compras.compra_detalles')

    {!! Form::close() !!}

</div>
@endsection

resources/views/compras/index.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1 class="pull-left">Compras</h1>
        <h1 class="pull-right">
            @can('compras.create')
           <a class="btn btn-primary pull-right" style="margin-top: -10px;margin-bottom: 5px" href="{{ route('compras.create') }}">Agregar</a>
            @endcan
        </h1>
    </section>
    <div class="content">
        <div class="clearfix"></div>

        @include('flash::message')

        <div class="clearfix"></div>
        <div class="box box-primary">
            <div class="box-body">
                    @include('compras.table')
            </div>
        </div>
        <div class="text-center">
        
        </div>
    </div>
@endsection

resources/views/compras/show.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Compras
        </h1>
    </section>
    <div class="content">
        <div class="box box-primary">
            <div class="box-body">
                <div class="row" style="padding-left: 20px">
                    @include('compras.show_fields')
                    <a href="{{ route('compras.index') }}" class="btn btn-default">Atrás</a>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/compras/show_fields.blade.php
<!-- Fecha Field -->
<div class="form-group">
    {!! Form::label('fecha', 'Fecha de compra:') !!}
    <p>{{ $compras->fecha->format('Y-m-d') }}</p>
</div>

<!-- Total Field -->
<div class="form-group">
    {!! Form::label('total', 'Total:') !!}
    <p>{{ $compras->total }}</p>
</div>

<!-- Proveedor Field -->
<div class="form-group">
    {!! Form::label('proveedor', 'Proveedor:') !!}
    <p>{{ $proveedor[0]->nombre }}</p>
</div>

<!-- Usuario Field -->
<div class="form-group">
    {!! Form::label('usuario', 'Usuario que hizo el registro:') !!}
    <p>{{ $compras->usuario }}</p>
</div>

<!-- Created At Field -->
<div class="form-group">
    {!! Form::label('created_at', 'Registrado el:') !!}
    <p>{{ $compras->created_at }}</p>
</div>

<div class="table-responsive">
    <table class="table" id="comprasDetalles-table">
        <thead>
            <tr>
                <th>Código de producto</th>
                <th>Nombre y descripción</th>
                <th>Cantidad comprada</th>
                <th>Precio de compra</th>
                <th>Subtotal</th>
            </tr>
        </thead>
        <tbody>
            @foreach($comprasDetalles as $detalle)
            <tr>
                <td>{{ $detalle->codigo }}</td>
                <td>{{ $detalle->descipcion }}</td>
                <td>{{ $detalle->cantidad }}</td>
                <td>{{ $detalle->precioCompra }}</td>
                <td>{{ $detalle->subtotal }}</td>
            </tr>
            @endforeach
        </tbody>
    </table>
</div>

resources/views/compras/table.blade.php
<div class="table-responsive">
    <table class="table" id="compras-table">
        <thead>
            <tr>
                <th>Fecha</th>
        <th>Total</th>
        <th>Proveedor</th>
        <th>Usuario</th>
            </tr>
        </thead>
        <tbody>
        @foreach($compras as $compra)
            <tr>
            <td>{{ $compra->fecha }}</td>
            <td>{{ $compra->total }}</td>
            <td>{{ $compra->nombre }}</td>
            <td>{{ $compra->usuario }}</td>
                <td>
                    <div class='btn-group'>
                        @can('compras.show')
                        <a href="{{ route('compras.show', [$compra->id]) }}" class='btn btn-default'><i class="icofont-eye"></i></a>
                        @endcan
                    </div>
                </td>
            </tr>
        @endforeach
        </tbody>
    </table>
    {{$compras -> links()}}
</div>